### ISSUE TITLE
The "metadata.json" file for the box 'aws' was not found.

### ISSUE THREAD

**Issue by aces2808** [rbprado/provision-freeipa-aws#1]
Any ideas on how to resolve this one?

**Comment by rbprado** [comment]
Hello buddy!
Please, could you please describe your steps and when the error is throw, with the full output.

**Comment by aces2808** [comment]
Found a solution, I just need to define my own metadata file.

**Comment by rbprado** [comment]
So, just for clarification, is this metadata file faulting here on the repository?
Have you been able to bring up your freeipa instance?
